// agent.proto — agent ↔ Connector 协议冻结基线（platform-architecture.md §6.1）。
// v1 冻结纪律：只增不改；字段号不复用；废弃用 reserved。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_Control_FullMethodName = "/tomai.agent.v1.AgentGateway/Control"
	AgentGateway_Metrics_FullMethodName = "/tomai.agent.v1.AgentGateway/Metrics"
	AgentGateway_Reports_FullMethodName = "/tomai.agent.v1.AgentGateway/Reports"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayClient interface {
	// 控制流：agent 发 AgentControlFrame，收 GatewayControlFrame。
	// 首帧必须 AgentHello，未完成握手不得发送指标与结果。
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControlFrame, GatewayControlFrame], error)
	// 指标流：双向流，逐批 ACK（agent 凭 ACK 推进内存缓冲/WAL 游标）。
	Metrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricBatch, MetricAck], error)
	// 可靠流：结果/审计/inventory，平台持久化后才最终 ACK。
	Reports(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReliableReport, ReportAck], error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControlFrame, GatewayControlFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentControlFrame, GatewayControlFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ControlClient = grpc.BidiStreamingClient[AgentControlFrame, GatewayControlFrame]

func (c *agentGatewayClient) Metrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricBatch, MetricAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[1], AgentGateway_Metrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricBatch, MetricAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_MetricsClient = grpc.BidiStreamingClient[MetricBatch, MetricAck]

func (c *agentGatewayClient) Reports(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReliableReport, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[2], AgentGateway_Reports_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReliableReport, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ReportsClient = grpc.BidiStreamingClient[ReliableReport, ReportAck]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
type AgentGatewayServer interface {
	// 控制流：agent 发 AgentControlFrame，收 GatewayControlFrame。
	// 首帧必须 AgentHello，未完成握手不得发送指标与结果。
	Control(grpc.BidiStreamingServer[AgentControlFrame, GatewayControlFrame]) error
	// 指标流：双向流，逐批 ACK（agent 凭 ACK 推进内存缓冲/WAL 游标）。
	Metrics(grpc.BidiStreamingServer[MetricBatch, MetricAck]) error
	// 可靠流：结果/审计/inventory，平台持久化后才最终 ACK。
	Reports(grpc.BidiStreamingServer[ReliableReport, ReportAck]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) Control(grpc.BidiStreamingServer[AgentControlFrame, GatewayControlFrame]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAgentGatewayServer) Metrics(grpc.BidiStreamingServer[MetricBatch, MetricAck]) error {
	return status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedAgentGatewayServer) Reports(grpc.BidiStreamingServer[ReliableReport, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method Reports not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Control(&grpc.GenericServerStream[AgentControlFrame, GatewayControlFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ControlServer = grpc.BidiStreamingServer[AgentControlFrame, GatewayControlFrame]

func _AgentGateway_Metrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Metrics(&grpc.GenericServerStream[MetricBatch, MetricAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_MetricsServer = grpc.BidiStreamingServer[MetricBatch, MetricAck]

func _AgentGateway_Reports_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Reports(&grpc.GenericServerStream[ReliableReport, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ReportsServer = grpc.BidiStreamingServer[ReliableReport, ReportAck]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tomai.agent.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _AgentGateway_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Metrics",
			Handler:       _AgentGateway_Metrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Reports",
			Handler:       _AgentGateway_Reports_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}

const (
	AgentBootstrap_Register_FullMethodName          = "/tomai.agent.v1.AgentBootstrap/Register"
	AgentBootstrap_RotateCertificate_FullMethodName = "/tomai.agent.v1.AgentBootstrap/RotateCertificate"
)

// AgentBootstrapClient is the client API for AgentBootstrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentBootstrapClient interface {
	// 注册：server-auth TLS + bootstrap token，幂等 enrollment_request_id。
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 证书轮换（M5b 启用）。
	RotateCertificate(ctx context.Context, in *RotateCertRequest, opts ...grpc.CallOption) (*RotateCertResponse, error)
}

type agentBootstrapClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentBootstrapClient(cc grpc.ClientConnInterface) AgentBootstrapClient {
	return &agentBootstrapClient{cc}
}

func (c *agentBootstrapClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentBootstrap_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentBootstrapClient) RotateCertificate(ctx context.Context, in *RotateCertRequest, opts ...grpc.CallOption) (*RotateCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCertResponse)
	err := c.cc.Invoke(ctx, AgentBootstrap_RotateCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentBootstrapServer is the server API for AgentBootstrap service.
// All implementations must embed UnimplementedAgentBootstrapServer
// for forward compatibility.
type AgentBootstrapServer interface {
	// 注册：server-auth TLS + bootstrap token，幂等 enrollment_request_id。
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 证书轮换（M5b 启用）。
	RotateCertificate(context.Context, *RotateCertRequest) (*RotateCertResponse, error)
	mustEmbedUnimplementedAgentBootstrapServer()
}

// UnimplementedAgentBootstrapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentBootstrapServer struct{}

func (UnimplementedAgentBootstrapServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentBootstrapServer) RotateCertificate(context.Context, *RotateCertRequest) (*RotateCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCertificate not implemented")
}
func (UnimplementedAgentBootstrapServer) mustEmbedUnimplementedAgentBootstrapServer() {}
func (UnimplementedAgentBootstrapServer) testEmbeddedByValue()                        {}

// UnsafeAgentBootstrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentBootstrapServer will
// result in compilation errors.
type UnsafeAgentBootstrapServer interface {
	mustEmbedUnimplementedAgentBootstrapServer()
}

func RegisterAgentBootstrapServer(s grpc.ServiceRegistrar, srv AgentBootstrapServer) {
	// If the following call panics, it indicates UnimplementedAgentBootstrapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentBootstrap_ServiceDesc, srv)
}

func _AgentBootstrap_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentBootstrapServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentBootstrap_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentBootstrapServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentBootstrap_RotateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentBootstrapServer).RotateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentBootstrap_RotateCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentBootstrapServer).RotateCertificate(ctx, req.(*RotateCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentBootstrap_ServiceDesc is the grpc.ServiceDesc for AgentBootstrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentBootstrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tomai.agent.v1.AgentBootstrap",
	HandlerType: (*AgentBootstrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentBootstrap_Register_Handler,
		},
		{
			MethodName: "RotateCertificate",
			Handler:    _AgentBootstrap_RotateCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
