// agent.proto — agent ↔ Connector 协议冻结基线（platform-architecture.md §6.1）。
// v1 冻结纪律：只增不改；字段号不复用；废弃用 reserved。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportKind int32

const (
	ReportKind_REPORT_KIND_UNSPECIFIED ReportKind = 0
	ReportKind_REPORT_KIND_RESULTS     ReportKind = 1
	ReportKind_REPORT_KIND_AUDIT       ReportKind = 2
	ReportKind_REPORT_KIND_INVENTORY   ReportKind = 3
)

// Enum value maps for ReportKind.
var (
	ReportKind_name = map[int32]string{
		0: "REPORT_KIND_UNSPECIFIED",
		1: "REPORT_KIND_RESULTS",
		2: "REPORT_KIND_AUDIT",
		3: "REPORT_KIND_INVENTORY",
	}
	ReportKind_value = map[string]int32{
		"REPORT_KIND_UNSPECIFIED": 0,
		"REPORT_KIND_RESULTS":     1,
		"REPORT_KIND_AUDIT":       2,
		"REPORT_KIND_INVENTORY":   3,
	}
)

func (x ReportKind) Enum() *ReportKind {
	p := new(ReportKind)
	*p = x
	return p
}

func (x ReportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ReportKind) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x ReportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportKind.Descriptor instead.
func (ReportKind) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 毫秒(UTC)
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SentAt        int64                  `protobuf:"varint,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Samples       []*Metric              `protobuf:"bytes,4,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *MetricBatch) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MetricBatch) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *MetricBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MetricBatch) GetSamples() []*Metric {
	if x != nil {
		return x.Samples
	}
	return nil
}

type MetricAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastAckedSequence uint64                 `protobuf:"varint,1,opt,name=last_acked_sequence,json=lastAckedSequence,proto3" json:"last_acked_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricAck) Reset() {
	*x = MetricAck{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAck) ProtoMessage() {}

func (x *MetricAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAck.ProtoReflect.Descriptor instead.
func (*MetricAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *MetricAck) GetLastAckedSequence() uint64 {
	if x != nil {
		return x.LastAckedSequence
	}
	return 0
}

type ReliableItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // cmd_id / event_id / report_id，平台按此去重
	Kind          ReportKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=tomai.agent.v1.ReportKind" json:"kind,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON（proto 二期可换结构化）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReliableItem) Reset() {
	*x = ReliableItem{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReliableItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliableItem) ProtoMessage() {}

func (x *ReliableItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliableItem.ProtoReflect.Descriptor instead.
func (*ReliableItem) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReliableItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReliableItem) GetKind() ReportKind {
	if x != nil {
		return x.Kind
	}
	return ReportKind_REPORT_KIND_UNSPECIFIED
}

func (x *ReliableItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ReliableItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReliableReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Kind          ReportKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=tomai.agent.v1.ReportKind" json:"kind,omitempty"`
	SentAt        int64                  `protobuf:"varint,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Items         []*ReliableItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReliableReport) Reset() {
	*x = ReliableReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReliableReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliableReport) ProtoMessage() {}

func (x *ReliableReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliableReport.ProtoReflect.Descriptor instead.
func (*ReliableReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReliableReport) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReliableReport) GetKind() ReportKind {
	if x != nil {
		return x.Kind
	}
	return ReportKind_REPORT_KIND_UNSPECIFIED
}

func (x *ReliableReport) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *ReliableReport) GetItems() []*ReliableItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ReportKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=tomai.agent.v1.ReportKind" json:"kind,omitempty"`
	AckedIds      []string               `protobuf:"bytes,2,rep,name=acked_ids,json=ackedIds,proto3" json:"acked_ids,omitempty"` // 平台已持久化的条目
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ReportAck) GetKind() ReportKind {
	if x != nil {
		return x.Kind
	}
	return ReportKind_REPORT_KIND_UNSPECIFIED
}

func (x *ReportAck) GetAckedIds() []string {
	if x != nil {
		return x.AckedIds
	}
	return nil
}

type AgentControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AgentControlFrame_Hello
	//	*AgentControlFrame_Heartbeat
	//	*AgentControlFrame_CommandAck
	//	*AgentControlFrame_CommandEvent
	//	*AgentControlFrame_ConfigApplyAck
	//	*AgentControlFrame_Event
	Frame         isAgentControlFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentControlFrame) Reset() {
	*x = AgentControlFrame{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentControlFrame) ProtoMessage() {}

func (x *AgentControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentControlFrame.ProtoReflect.Descriptor instead.
func (*AgentControlFrame) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentControlFrame) GetFrame() isAgentControlFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AgentControlFrame) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentControlFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentControlFrame) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *AgentControlFrame) GetCommandEvent() *CommandEvent {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_CommandEvent); ok {
			return x.CommandEvent
		}
	}
	return nil
}

func (x *AgentControlFrame) GetConfigApplyAck() *ConfigApplyAck {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_ConfigApplyAck); ok {
			return x.ConfigApplyAck
		}
	}
	return nil
}

func (x *AgentControlFrame) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Frame.(*AgentControlFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentControlFrame_Frame interface {
	isAgentControlFrame_Frame()
}

type AgentControlFrame_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentControlFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentControlFrame_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,3,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type AgentControlFrame_CommandEvent struct {
	CommandEvent *CommandEvent `protobuf:"bytes,4,opt,name=command_event,json=commandEvent,proto3,oneof"`
}

type AgentControlFrame_ConfigApplyAck struct {
	ConfigApplyAck *ConfigApplyAck `protobuf:"bytes,5,opt,name=config_apply_ack,json=configApplyAck,proto3,oneof"`
}

type AgentControlFrame_Event struct {
	Event *AgentEvent `protobuf:"bytes,6,opt,name=event,proto3,oneof"`
}

func (*AgentControlFrame_Hello) isAgentControlFrame_Frame() {}

func (*AgentControlFrame_Heartbeat) isAgentControlFrame_Frame() {}

func (*AgentControlFrame_CommandAck) isAgentControlFrame_Frame() {}

func (*AgentControlFrame_CommandEvent) isAgentControlFrame_Frame() {}

func (*AgentControlFrame_ConfigApplyAck) isAgentControlFrame_Frame() {}

func (*AgentControlFrame_Event) isAgentControlFrame_Frame() {}

type GatewayControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*GatewayControlFrame_Welcome
	//	*GatewayControlFrame_Command
	//	*GatewayControlFrame_Cancel
	//	*GatewayControlFrame_ConfigPush
	//	*GatewayControlFrame_ReconnectHint
	//	*GatewayControlFrame_Fence
	Frame         isGatewayControlFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayControlFrame) Reset() {
	*x = GatewayControlFrame{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayControlFrame) ProtoMessage() {}

func (x *GatewayControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayControlFrame.ProtoReflect.Descriptor instead.
func (*GatewayControlFrame) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayControlFrame) GetFrame() isGatewayControlFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *GatewayControlFrame) GetWelcome() *GatewayWelcome {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *GatewayControlFrame) GetCommand() *CommandEnvelope {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayControlFrame) GetCancel() *CancelCommand {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *GatewayControlFrame) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *GatewayControlFrame) GetReconnectHint() *ReconnectHint {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_ReconnectHint); ok {
			return x.ReconnectHint
		}
	}
	return nil
}

func (x *GatewayControlFrame) GetFence() *FenceNotice {
	if x != nil {
		if x, ok := x.Frame.(*GatewayControlFrame_Fence); ok {
			return x.Fence
		}
	}
	return nil
}

type isGatewayControlFrame_Frame interface {
	isGatewayControlFrame_Frame()
}

type GatewayControlFrame_Welcome struct {
	Welcome *GatewayWelcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type GatewayControlFrame_Command struct {
	Command *CommandEnvelope `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type GatewayControlFrame_Cancel struct {
	Cancel *CancelCommand `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type GatewayControlFrame_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,4,opt,name=config_push,json=configPush,proto3,oneof"`
}

type GatewayControlFrame_ReconnectHint struct {
	ReconnectHint *ReconnectHint `protobuf:"bytes,5,opt,name=reconnect_hint,json=reconnectHint,proto3,oneof"`
}

type GatewayControlFrame_Fence struct {
	Fence *FenceNotice `protobuf:"bytes,6,opt,name=fence,proto3,oneof"`
}

func (*GatewayControlFrame_Welcome) isGatewayControlFrame_Frame() {}

func (*GatewayControlFrame_Command) isGatewayControlFrame_Frame() {}

func (*GatewayControlFrame_Cancel) isGatewayControlFrame_Frame() {}

func (*GatewayControlFrame_ConfigPush) isGatewayControlFrame_Frame() {}

func (*GatewayControlFrame_ReconnectHint) isGatewayControlFrame_Frame() {}

func (*GatewayControlFrame_Fence) isGatewayControlFrame_Frame() {}

type AgentHello struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AssetId              string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	BootId               string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	AgentVersion         string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolMinVersion   uint32                 `protobuf:"varint,4,opt,name=protocol_min_version,json=protocolMinVersion,proto3" json:"protocol_min_version,omitempty"`
	ProtocolMaxVersion   uint32                 `protobuf:"varint,5,opt,name=protocol_max_version,json=protocolMaxVersion,proto3" json:"protocol_max_version,omitempty"`
	ActionCatalogVersion string                 `protobuf:"bytes,6,opt,name=action_catalog_version,json=actionCatalogVersion,proto3" json:"action_catalog_version,omitempty"`
	CurrentConfigVersion string                 `protobuf:"bytes,7,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentHello) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AgentHello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetProtocolMinVersion() uint32 {
	if x != nil {
		return x.ProtocolMinVersion
	}
	return 0
}

func (x *AgentHello) GetProtocolMaxVersion() uint32 {
	if x != nil {
		return x.ProtocolMaxVersion
	}
	return 0
}

func (x *AgentHello) GetActionCatalogVersion() string {
	if x != nil {
		return x.ActionCatalogVersion
	}
	return ""
}

func (x *AgentHello) GetCurrentConfigVersion() string {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return ""
}

type GatewayWelcome struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionEpoch         uint64                 `protobuf:"varint,2,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	ServerTime           int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	HeartbeatIntervalSec uint32                 `protobuf:"varint,4,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	MaxInflightReports   uint32                 `protobuf:"varint,5,opt,name=max_inflight_reports,json=maxInflightReports,proto3" json:"max_inflight_reports,omitempty"`
	TargetConfigVersion  string                 `protobuf:"bytes,6,opt,name=target_config_version,json=targetConfigVersion,proto3" json:"target_config_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GatewayWelcome) Reset() {
	*x = GatewayWelcome{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayWelcome) ProtoMessage() {}

func (x *GatewayWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayWelcome.ProtoReflect.Descriptor instead.
func (*GatewayWelcome) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayWelcome) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayWelcome) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *GatewayWelcome) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *GatewayWelcome) GetHeartbeatIntervalSec() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *GatewayWelcome) GetMaxInflightReports() uint32 {
	if x != nil {
		return x.MaxInflightReports
	}
	return 0
}

func (x *GatewayWelcome) GetTargetConfigVersion() string {
	if x != nil {
		return x.TargetConfigVersion
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        int64                  `protobuf:"varint,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// 指令信封：签名在投递时由平台 Signer 完成（M5c 验签启用）。
type CommandEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSec    uint32                 `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519(以上字段规范序列化)，空=开发态不验签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CommandEnvelope) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandEnvelope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CommandEnvelope) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CommandEnvelope) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *CommandEnvelope) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *CommandEnvelope) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CommandEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CommandEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CancelCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommand) Reset() {
	*x = CancelCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommand) ProtoMessage() {}

func (x *CancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommand.ProtoReflect.Descriptor instead.
func (*CancelCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CancelCommand) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // REJECTED_BUSY / REJECTED_POLICY / ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CommandAck) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CommandAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type CommandEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         string                 `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // running / finished
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CommandEvent) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *CommandEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CommandEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	SignedConfig  []byte                 `protobuf:"bytes,2,opt,name=signed_config,json=signedConfig,proto3" json:"signed_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigPush) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigPush) GetSignedConfig() []byte {
	if x != nil {
		return x.SignedConfig
	}
	return nil
}

type ConfigApplyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Applied       bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplyAck) Reset() {
	*x = ConfigApplyAck{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyAck) ProtoMessage() {}

func (x *ConfigApplyAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyAck.ProtoReflect.Descriptor instead.
func (*ConfigApplyAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigApplyAck) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigApplyAck) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ConfigApplyAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReconnectHint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReconnectAfterSec uint32                 `protobuf:"varint,1,opt,name=reconnect_after_sec,json=reconnectAfterSec,proto3" json:"reconnect_after_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconnectHint) Reset() {
	*x = ReconnectHint{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectHint) ProtoMessage() {}

func (x *ReconnectHint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectHint.ProtoReflect.Descriptor instead.
func (*ReconnectHint) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ReconnectHint) GetReconnectAfterSec() uint32 {
	if x != nil {
		return x.ReconnectAfterSec
	}
	return 0
}

type FenceNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionEpoch  uint64                 `protobuf:"varint,1,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceNotice) Reset() {
	*x = FenceNotice{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceNotice) ProtoMessage() {}

func (x *FenceNotice) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceNotice.ProtoReflect.Descriptor instead.
func (*FenceNotice) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FenceNotice) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *FenceNotice) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *AgentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *AgentEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type RegisterRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentRequestId string                 `protobuf:"bytes,1,opt,name=enrollment_request_id,json=enrollmentRequestId,proto3" json:"enrollment_request_id,omitempty"` // 幂等键
	BootstrapToken      string                 `protobuf:"bytes,2,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	Materials           map[string]string      `protobuf:"bytes,3,rep,name=materials,proto3" json:"materials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // machine_id/hostname/kernel/arch/os
	CsrDer              []byte                 `protobuf:"bytes,4,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`                                                                   // v1.1 增补：PKCS#10 CSR（CN 由平台改写为 asset_id）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterRequest) GetEnrollmentRequestId() string {
	if x != nil {
		return x.EnrollmentRequestId
	}
	return ""
}

func (x *RegisterRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *RegisterRequest) GetMaterials() map[string]string {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *RegisterRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RegisterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssetId        string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	GatewayAddr    string                 `protobuf:"bytes,2,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	CertificateDer []byte                 `protobuf:"bytes,3,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"` // v1.1 增补：平台 PKI 签发的客户端证书（CN=asset_id）
	CaDer          []byte                 `protobuf:"bytes,4,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`                            // 根 CA（ pinning 用）
	NotAfter       int64                  `protobuf:"varint,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`                  // 证书到期（Unix 秒），驱动轮换
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *RegisterResponse) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

func (x *RegisterResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *RegisterResponse) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *RegisterResponse) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type RotateCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCertRequest) Reset() {
	*x = RotateCertRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCertRequest) ProtoMessage() {}

func (x *RotateCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCertRequest.ProtoReflect.Descriptor instead.
func (*RotateCertRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *RotateCertRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *RotateCertRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RotateCertResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificateDer []byte                 `protobuf:"bytes,1,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	NotAfter       int64                  `protobuf:"varint,2,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RotateCertResponse) Reset() {
	*x = RotateCertResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCertResponse) ProtoMessage() {}

func (x *RotateCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCertResponse.ProtoReflect.Descriptor instead.
func (*RotateCertResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RotateCertResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *RotateCertResponse) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x0etomai.agent.v1\"\xcb\x01\n" +
	"\x06Metric\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12:\n" +
	"\x06labels\x18\x04 \x03(\v2\".tomai.agent.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\vMetricBatch\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\x03R\x06sentAt\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x120\n" +
	"\asamples\x18\x04 \x03(\v2\x16.tomai.agent.v1.MetricR\asamples\";\n" +
	"\tMetricAck\x12.\n" +
	"\x13last_acked_sequence\x18\x01 \x01(\x04R\x11lastAckedSequence\"\x87\x01\n" +
	"\fReliableItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.tomai.agent.v1.ReportKindR\x04kind\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xa8\x01\n" +
	"\x0eReliableReport\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.tomai.agent.v1.ReportKindR\x04kind\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\x03R\x06sentAt\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.tomai.agent.v1.ReliableItemR\x05items\"X\n" +
	"\tReportAck\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.tomai.agent.v1.ReportKindR\x04kind\x12\x1b\n" +
	"\tacked_ids\x18\x02 \x03(\tR\backedIds\"\x8f\x03\n" +
	"\x11AgentControlFrame\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.tomai.agent.v1.AgentHelloH\x00R\x05hello\x129\n" +
	"\theartbeat\x18\x02 \x01(\v2\x19.tomai.agent.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\vcommand_ack\x18\x03 \x01(\v2\x1a.tomai.agent.v1.CommandAckH\x00R\n" +
	"commandAck\x12C\n" +
	"\rcommand_event\x18\x04 \x01(\v2\x1c.tomai.agent.v1.CommandEventH\x00R\fcommandEvent\x12J\n" +
	"\x10config_apply_ack\x18\x05 \x01(\v2\x1e.tomai.agent.v1.ConfigApplyAckH\x00R\x0econfigApplyAck\x122\n" +
	"\x05event\x18\x06 \x01(\v2\x1a.tomai.agent.v1.AgentEventH\x00R\x05eventB\a\n" +
	"\x05frame\"\x8c\x03\n" +
	"\x13GatewayControlFrame\x12:\n" +
	"\awelcome\x18\x01 \x01(\v2\x1e.tomai.agent.v1.GatewayWelcomeH\x00R\awelcome\x12;\n" +
	"\acommand\x18\x02 \x01(\v2\x1f.tomai.agent.v1.CommandEnvelopeH\x00R\acommand\x127\n" +
	"\x06cancel\x18\x03 \x01(\v2\x1d.tomai.agent.v1.CancelCommandH\x00R\x06cancel\x12=\n" +
	"\vconfig_push\x18\x04 \x01(\v2\x1a.tomai.agent.v1.ConfigPushH\x00R\n" +
	"configPush\x12F\n" +
	"\x0ereconnect_hint\x18\x05 \x01(\v2\x1d.tomai.agent.v1.ReconnectHintH\x00R\rreconnectHint\x123\n" +
	"\x05fence\x18\x06 \x01(\v2\x1b.tomai.agent.v1.FenceNoticeH\x00R\x05fenceB\a\n" +
	"\x05frame\"\xb5\x02\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x120\n" +
	"\x14protocol_min_version\x18\x04 \x01(\rR\x12protocolMinVersion\x120\n" +
	"\x14protocol_max_version\x18\x05 \x01(\rR\x12protocolMaxVersion\x124\n" +
	"\x16action_catalog_version\x18\x06 \x01(\tR\x14actionCatalogVersion\x124\n" +
	"\x16current_config_version\x18\a \x01(\tR\x14currentConfigVersion\"\x91\x02\n" +
	"\x0eGatewayWelcome\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x02 \x01(\x04R\fsessionEpoch\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x124\n" +
	"\x16heartbeat_interval_sec\x18\x04 \x01(\rR\x14heartbeatIntervalSec\x120\n" +
	"\x14max_inflight_reports\x18\x05 \x01(\rR\x12maxInflightReports\x122\n" +
	"\x15target_config_version\x18\x06 \x01(\tR\x13targetConfigVersion\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\asent_at\x18\x01 \x01(\x03R\x06sentAt\"\xd1\x02\n" +
	"\x0fCommandEnvelope\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12C\n" +
	"\x06params\x18\x03 \x03(\v2+.tomai.agent.v1.CommandEnvelope.ParamsEntryR\x06params\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\rR\n" +
	"timeoutSec\x12\x1b\n" +
	"\tissued_at\x18\x05 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\rCancelCommand\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\"d\n" +
	"\n" +
	"CommandAck\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"S\n" +
	"\fCommandEvent\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\tR\x05cmdId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"X\n" +
	"\n" +
	"ConfigPush\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12#\n" +
	"\rsigned_config\x18\x02 \x01(\fR\fsignedConfig\"g\n" +
	"\x0eConfigApplyAck\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"?\n" +
	"\rReconnectHint\x12.\n" +
	"\x13reconnect_after_sec\x18\x01 \x01(\rR\x11reconnectAfterSec\"J\n" +
	"\vFenceNotice\x12#\n" +
	"\rsession_epoch\x18\x01 \x01(\x04R\fsessionEpoch\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd7\x01\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1f\n" +
	"\voccurred_at\x18\x02 \x01(\x03R\n" +
	"occurredAt\x12J\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2*.tomai.agent.v1.AgentEvent.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\x0fRegisterRequest\x122\n" +
	"\x15enrollment_request_id\x18\x01 \x01(\tR\x13enrollmentRequestId\x12'\n" +
	"\x0fbootstrap_token\x18\x02 \x01(\tR\x0ebootstrapToken\x12L\n" +
	"\tmaterials\x18\x03 \x03(\v2..tomai.agent.v1.RegisterRequest.MaterialsEntryR\tmaterials\x12\x17\n" +
	"\acsr_der\x18\x04 \x01(\fR\x06csrDer\x1a<\n" +
	"\x0eMaterialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12!\n" +
	"\fgateway_addr\x18\x02 \x01(\tR\vgatewayAddr\x12'\n" +
	"\x0fcertificate_der\x18\x03 \x01(\fR\x0ecertificateDer\x12\x15\n" +
	"\x06ca_der\x18\x04 \x01(\fR\x05caDer\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\x03R\bnotAfter\"G\n" +
	"\x11RotateCertRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\"Z\n" +
	"\x12RotateCertResponse\x12'\n" +
	"\x0fcertificate_der\x18\x01 \x01(\fR\x0ecertificateDer\x12\x1b\n" +
	"\tnot_after\x18\x02 \x01(\x03R\bnotAfter*t\n" +
	"\n" +
	"ReportKind\x12\x1b\n" +
	"\x17REPORT_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REPORT_KIND_RESULTS\x10\x01\x12\x15\n" +
	"\x11REPORT_KIND_AUDIT\x10\x02\x12\x19\n" +
	"\x15REPORT_KIND_INVENTORY\x10\x032\xf6\x01\n" +
	"\fAgentGateway\x12U\n" +
	"\aControl\x12!.tomai.agent.v1.AgentControlFrame\x1a#.tomai.agent.v1.GatewayControlFrame(\x010\x01\x12E\n" +
	"\aMetrics\x12\x1b.tomai.agent.v1.MetricBatch\x1a\x19.tomai.agent.v1.MetricAck(\x010\x01\x12H\n" +
	"\aReports\x12\x1e.tomai.agent.v1.ReliableReport\x1a\x19.tomai.agent.v1.ReportAck(\x010\x012\xbb\x01\n" +
	"\x0eAgentBootstrap\x12M\n" +
	"\bRegister\x12\x1f.tomai.agent.v1.RegisterRequest\x1a .tomai.agent.v1.RegisterResponse\x12Z\n" +
	"\x11RotateCertificate\x12!.tomai.agent.v1.RotateCertRequest\x1a\".tomai.agent.v1.RotateCertResponseB<Z:github.com/tomhu/tom_ai_agent/internal/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_agent_v1_agent_proto_goTypes = []any{
	(ReportKind)(0),             // 0: tomai.agent.v1.ReportKind
	(*Metric)(nil),              // 1: tomai.agent.v1.Metric
	(*MetricBatch)(nil),         // 2: tomai.agent.v1.MetricBatch
	(*MetricAck)(nil),           // 3: tomai.agent.v1.MetricAck
	(*ReliableItem)(nil),        // 4: tomai.agent.v1.ReliableItem
	(*ReliableReport)(nil),      // 5: tomai.agent.v1.ReliableReport
	(*ReportAck)(nil),           // 6: tomai.agent.v1.ReportAck
	(*AgentControlFrame)(nil),   // 7: tomai.agent.v1.AgentControlFrame
	(*GatewayControlFrame)(nil), // 8: tomai.agent.v1.GatewayControlFrame
	(*AgentHello)(nil),          // 9: tomai.agent.v1.AgentHello
	(*GatewayWelcome)(nil),      // 10: tomai.agent.v1.GatewayWelcome
	(*Heartbeat)(nil),           // 11: tomai.agent.v1.Heartbeat
	(*CommandEnvelope)(nil),     // 12: tomai.agent.v1.CommandEnvelope
	(*CancelCommand)(nil),       // 13: tomai.agent.v1.CancelCommand
	(*CommandAck)(nil),          // 14: tomai.agent.v1.CommandAck
	(*CommandEvent)(nil),        // 15: tomai.agent.v1.CommandEvent
	(*ConfigPush)(nil),          // 16: tomai.agent.v1.ConfigPush
	(*ConfigApplyAck)(nil),      // 17: tomai.agent.v1.ConfigApplyAck
	(*ReconnectHint)(nil),       // 18: tomai.agent.v1.ReconnectHint
	(*FenceNotice)(nil),         // 19: tomai.agent.v1.FenceNotice
	(*AgentEvent)(nil),          // 20: tomai.agent.v1.AgentEvent
	(*RegisterRequest)(nil),     // 21: tomai.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 22: tomai.agent.v1.RegisterResponse
	(*RotateCertRequest)(nil),   // 23: tomai.agent.v1.RotateCertRequest
	(*RotateCertResponse)(nil),  // 24: tomai.agent.v1.RotateCertResponse
	nil,                         // 25: tomai.agent.v1.Metric.LabelsEntry
	nil,                         // 26: tomai.agent.v1.CommandEnvelope.ParamsEntry
	nil,                         // 27: tomai.agent.v1.AgentEvent.AttributesEntry
	nil,                         // 28: tomai.agent.v1.RegisterRequest.MaterialsEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	25, // 0: tomai.agent.v1.Metric.labels:type_name -> tomai.agent.v1.Metric.LabelsEntry
	1,  // 1: tomai.agent.v1.MetricBatch.samples:type_name -> tomai.agent.v1.Metric
	0,  // 2: tomai.agent.v1.ReliableItem.kind:type_name -> tomai.agent.v1.ReportKind
	0,  // 3: tomai.agent.v1.ReliableReport.kind:type_name -> tomai.agent.v1.ReportKind
	4,  // 4: tomai.agent.v1.ReliableReport.items:type_name -> tomai.agent.v1.ReliableItem
	0,  // 5: tomai.agent.v1.ReportAck.kind:type_name -> tomai.agent.v1.ReportKind
	9,  // 6: tomai.agent.v1.AgentControlFrame.hello:type_name -> tomai.agent.v1.AgentHello
	11, // 7: tomai.agent.v1.AgentControlFrame.heartbeat:type_name -> tomai.agent.v1.Heartbeat
	14, // 8: tomai.agent.v1.AgentControlFrame.command_ack:type_name -> tomai.agent.v1.CommandAck
	15, // 9: tomai.agent.v1.AgentControlFrame.command_event:type_name -> tomai.agent.v1.CommandEvent
	17, // 10: tomai.agent.v1.AgentControlFrame.config_apply_ack:type_name -> tomai.agent.v1.ConfigApplyAck
	20, // 11: tomai.agent.v1.AgentControlFrame.event:type_name -> tomai.agent.v1.AgentEvent
	10, // 12: tomai.agent.v1.GatewayControlFrame.welcome:type_name -> tomai.agent.v1.GatewayWelcome
	12, // 13: tomai.agent.v1.GatewayControlFrame.command:type_name -> tomai.agent.v1.CommandEnvelope
	13, // 14: tomai.agent.v1.GatewayControlFrame.cancel:type_name -> tomai.agent.v1.CancelCommand
	16, // 15: tomai.agent.v1.GatewayControlFrame.config_push:type_name -> tomai.agent.v1.ConfigPush
	18, // 16: tomai.agent.v1.GatewayControlFrame.reconnect_hint:type_name -> tomai.agent.v1.ReconnectHint
	19, // 17: tomai.agent.v1.GatewayControlFrame.fence:type_name -> tomai.agent.v1.FenceNotice
	26, // 18: tomai.agent.v1.CommandEnvelope.params:type_name -> tomai.agent.v1.CommandEnvelope.ParamsEntry
	27, // 19: tomai.agent.v1.AgentEvent.attributes:type_name -> tomai.agent.v1.AgentEvent.AttributesEntry
	28, // 20: tomai.agent.v1.RegisterRequest.materials:type_name -> tomai.agent.v1.RegisterRequest.MaterialsEntry
	7,  // 21: tomai.agent.v1.AgentGateway.Control:input_type -> tomai.agent.v1.AgentControlFrame
	2,  // 22: tomai.agent.v1.AgentGateway.Metrics:input_type -> tomai.agent.v1.MetricBatch
	5,  // 23: tomai.agent.v1.AgentGateway.Reports:input_type -> tomai.agent.v1.ReliableReport
	21, // 24: tomai.agent.v1.AgentBootstrap.Register:input_type -> tomai.agent.v1.RegisterRequest
	23, // 25: tomai.agent.v1.AgentBootstrap.RotateCertificate:input_type -> tomai.agent.v1.RotateCertRequest
	8,  // 26: tomai.agent.v1.AgentGateway.Control:output_type -> tomai.agent.v1.GatewayControlFrame
	3,  // 27: tomai.agent.v1.AgentGateway.Metrics:output_type -> tomai.agent.v1.MetricAck
	6,  // 28: tomai.agent.v1.AgentGateway.Reports:output_type -> tomai.agent.v1.ReportAck
	22, // 29: tomai.agent.v1.AgentBootstrap.Register:output_type -> tomai.agent.v1.RegisterResponse
	24, // 30: tomai.agent.v1.AgentBootstrap.RotateCertificate:output_type -> tomai.agent.v1.RotateCertResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentControlFrame_Hello)(nil),
		(*AgentControlFrame_Heartbeat)(nil),
		(*AgentControlFrame_CommandAck)(nil),
		(*AgentControlFrame_CommandEvent)(nil),
		(*AgentControlFrame_ConfigApplyAck)(nil),
		(*AgentControlFrame_Event)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*GatewayControlFrame_Welcome)(nil),
		(*GatewayControlFrame_Command)(nil),
		(*GatewayControlFrame_Cancel)(nil),
		(*GatewayControlFrame_ConfigPush)(nil),
		(*GatewayControlFrame_ReconnectHint)(nil),
		(*GatewayControlFrame_Fence)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
